Commerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls'))
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView,ProductPage,AboutPage,ContactPage,PostDetailView

urlpatterns = [
    path('',HomePageView.as_view(),name='home'),
    path('watches/',ProductPage.as_view(),name='watches'),
    path('about/',AboutPage.as_view(),name='about'),
    path('contact/',ContactPage.as_view(),name='contact'),
    path('post/<int:pk>/',PostDetailView.as_view(),name='post_detail')
]

pages/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.enums import TextChoices
from django.db.models.fields import CharField, TextField
from django.db.models.fields.files import ImageField

CATEGORY_CHOICES = (
    ('SW','SmartWatch'),
    ('P','Phone'),
    ('Pl','Planshet')
)
LABEL_CHOICES = (
    ('Y', 'primary'),
    ('D', 'danger'),
    ('S', 'secondry')
)
class Item(models.Model):
    image = models.ImageField(upload_to='images/')
    name = models.CharField(max_length=50)
    price = models.FloatField()
    condition = models.CharField(max_length=50)
    label = models.CharField(choices=LABEL_CHOICES, max_length=2)

    def __str__(self):
        return self.name

class Order(models.Model):
    image = models.ImageField(upload_to='images/')
    name = models.CharField(max_length=50)
    # category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    price = models.FloatField()
    condition = models.CharField(max_length=50)
    label = models.CharField(choices=LABEL_CHOICES, max_length=2)

    def __str__(self):
        return self.name

class Post(models.Model):
    image = models.ImageField(upload_to='images/')
    title = models.CharField(max_length=200)
    body = models.TextField()

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.pk})

# class CommentModel(models.Model):
#     blog = models.ForeignKey('Postmodel', on_delete=models.CASCADE, related_name='comments')
#     first_name = models.CharField(max_length=50)
#     last_name = models.CharField(max_length=50)
#     comment = models.TextField()
#     date_added = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return '%s - %s' % (self.blog.title,self.first_name)

#     # class Meta:
#     #     verbos_name = 'comment'
#     #     verbos_name_plural ='comments'

pages/forms.py
from pages.models import CommentModel

class CommentModelForm(forms.ModelForm):
    class Meta:
        model = CommentModel
        exclude = ['date_added','blog']

pages/views.py
from django.urls import reverse,reverse_lazy
from django.shortcuts import render
from django.http.request import HttpRequest
from django.views.generic.base import TemplateView
from django.views.generic import DetailView

from .models import Item,Order,Post

class HomePageView(TemplateView):
    template_name='home.html'
    def get(self, request):
        context = {
            'item':Item.objects.all(),
            'post': Post.objects.all(),
            }
        return render(request, self.template_name,context)

class PostDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'

class ProductPage(TemplateView):
    template_name = 'watches.html'
    def get(self, request):
        context = {
            'order':Order.objects.all(),
            }
        return render(request, self.template_name,context)


class AboutPage(TemplateView):
    template_name = 'about.html'

class ContactPage(TemplateView):
    template_name = 'contact.html'

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- about section -->

  <section class="about_section layout_padding">
    <div class="container  ">
      <div class="row">
        <div class="col-md-6 col-lg-5 ">
          <div class="img-box">
            <img src="{% static 'images/about-img.png' %}" alt="">
          </div>
        </div>
        <div class="col-md-6 col-lg-7">
          <div class="detail-box">
            <div class="heading_container">
              <h2>
                About Us
              </h2>
            </div>
            <p>
              There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration
              in some form, by injected humour, or randomised words which don't look even slightly believable. If you
              are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in
              the middle of text. All
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end about section -->

  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="footer_detail">
            <h4>
              About
            </h4>
            <p>
              Necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with
            </p>
            <div class="footer_social">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-linkedin" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="footer_contact">
            <h4>
              Reach at..
            </h4>
            <div class="contact_link_box">
              <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  Location
                </span>
              </a>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call +01 1234567890
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  demo@gmail.com
                </span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="footer_contact">
            <h4>
              Subscribe
            </h4>
            <form action="#">
              <input type="text" placeholder="Enter email" />
              <button type="submit">
                Subscribe
              </button>
            </form>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 footer-col">
          <div class="map_container">
            <div class="map">
              <div id="googleMap"></div>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-info">
        <p>
          &copy; <span id="displayYear"></span> All Rights Reserved By
          <a href="https://html.design/">Free Html Templates</a>
        </p>
      </div>
    </div>
  </footer>
  <!-- footer section -->

  <!-- jQery -->
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <!-- bootstrap js -->
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <!-- owl slider -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- custom js -->
  <script src="{% static 'js/custom.js' %}"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
  <!-- End Google Map -->
  {% endblock%}

</body>

</html>

templates/base.html
 {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
{% block title %}
  <title>Timups</title>
{% endblock %}
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>
  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
</head>
<body>
  <div class="hero_area">
    <div class="hero_social">
      <a href="">
        <i class="fa fa-instagram"  style="color: red" aria-hidden="true"></i>
      </a>
      <a href="">
        <i class="fa fa-facebook" style="color: blue" aria-hidden="true"></i>
      </a>
      <a href="">
        <i class="fa fa-youtube" style="color: red" aria-hidden="true"></i>
      </a>
      <a href="">
        <i class="fa fa-telegram" style="color: blue" aria-hidden="true"></i>
      </a>
    </div>
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="{% url 'home' %}">
            <span>
              Timups
            </span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="">Webtexno</span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'watches' %}"> Watches </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}"> About </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
              </li>
            </ul>
            <div class="user_option-box">
              <a href="">
                <i class="fa fa-user" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-cart-plus" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-search" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->
    {% block content %}

    {% endblock content %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body class="sub_page">
  <!-- contact section -->
  <section class="contact_section layout_padding">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="form_container">
            <div class="heading_container">
              <h2>
                Contact Us
              </h2>
            </div>
            <form action="" method='post'>
            {% csrf_token %}
              {{ form.as_p }}
              <div>
                <input type="text" placeholder="Full Name " />
              </div>
              <div>
                <input type="email" placeholder="Email" />
              </div>
              <div>
                <input type="text" placeholder="Phone number" />
              </div>
              <div>
                <input type="text" class="message-box" placeholder="Message" />
              </div>
              <div class="d-flex ">
                <button>
                  SEND
                </button>
              </div>
            </form>
          </div>
        </div>
        <div class="col-md-6">
          <div class="img-box">
            <img src="{% static 'images/contact-img.jpg' %}" alt="">
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- end contact section -->

{% endblock %}

{% url 'footer.html'%}

templates/footer.html
{% load static %}
<!-- footer section -->
<footer class="footer_section">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-lg-3 footer-col">
        <div class="footer_detail">
          <h4>
            About
          </h4>
          <p>
            Necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with
          </p>
          <div class="footer_social">
            <a href="">
              <i class="fa fa-instagram" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-facebook" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-youtube" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-telegram" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3 footer-col">
        <div class="footer_contact">
          <h4>
            Reach at..
          </h4>
          <div class="contact_link_box">
            <a href="">
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              <span>
                Location
              </span>
            </a>
            <a href="">
              <i class="fa fa-phone" aria-hidden="true"></i>
              <span>
                Call +01 1234567890
              </span>
            </a>
            <a href="">
              <i class="fa fa-envelope" aria-hidden="true"></i>
              <span>
                demo@gmail.com
              </span>
            </a>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3 footer-col">
        <div class="footer_contact">
          <h4>
            Subscribe
          </h4>
          <form action="#">
            <input type="text" placeholder="Enter email" />
            <button type="submit">
              Subscribe
            </button>
          </form>
        </div>
      </div>
      <div class="col-md-6 col-lg-3 footer-col">
        <div class="map_container">
          <div class="map">
            <div id="googleMap"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer-info">
      <p>
        &copy; <span id="displayYear"></span> All Rights Reserved By
        <a href="https://html.design/">Free Html Templates</a>
      </p>
    </div>
  </div>
</footer>
<!-- footer section -->
<!-- jQery -->
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
</script>
<!-- bootstrap js -->
<script src="{% static 'js/bootstrap.js' %}"></script>
<!-- owl slider -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
</script>
<!-- custom js -->
<script src="{% static 'js/custom.js' %}"></script>
<!-- Google Map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
<!-- End Google Map -->
<body>
<html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- slider section -->
    <section class="slider_section ">
    <div id="customCarousel1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="container-fluid ">
            <div class="row">
                <div class="col-md-6">
                <div class="detail-box">
                    <h1>Smart Watches</h1>
                    <p>
                    Shoxrux scelerisque felis ut orci condimentum laoreet. Integer nisi nisl, convallis et augue sit amet, lobortis semper quam.
                    </p>
                    <div class="btn-box">
                    <a href="{% url 'contact' %}" class="btn1">
                        Contact Us 
                    </a>
                    </div>
                </div>
                </div>
                <div class="col-md-6">
                <div class="img-box">
                    <img src="{% static 'images/slider-img.png' %}" alt="">
                </div>
                </div>
            </div>
            </div>
        </div>
        <div class="carousel-item ">
            <div class="container-fluid ">
            <div class="row">
                <div class="col-md-6">
                <div class="detail-box">
                    <h1>Smart Watches</h1>
                    <p>
                    Aenean scelerisque felis ut orci condimentum laoreet. Integer nisi nisl, convallis et augue sit amet, lobortis semper quam.
                    </p>
                    <div class="btn-box">
                    <a href="{% url 'contact' %}" class="btn1">
                        Contact Us
                    </a>
                    </div>
                </div>
                </div>
                <div class="col-md-6">
                <div class="img-box">
                    <img src="{% static 'images/slider-img.png' %}" alt="">
                </div>
                </div>
            </div>
            </div>
        </div>
        <div class="carousel-item ">
            <div class="container-fluid ">
            <div class="row">
                <div class="col-md-6">
                <div class="detail-box">
                    <h1>Smart Watches</h1>
                    <p>
                    Aenean scelerisque felis ut orci condimentum laoreet. Integer nisi nisl, convallis et augue sit amet, lobortis semper quam.
                    </p>
                    <div class="btn-box">
                    <a href="{% url 'contact' %}" class="btn1">
                        Contact Us
                    </a>
                    </div>
                </div>
                </div>
                <div class="col-md-6">
                <div class="img-box">
                    <img src="{% static 'images/slider-img.png' %}" alt="">
                </div>
                </div>
            </div>
            </div>
        </div>
        </div>
        <ol class="carousel-indicators">
        <li data-target="#customCarousel1" data-slide-to="0" class="active"></li>
        <li data-target="#customCarousel1" data-slide-to="1"></li>
        <li data-target="#customCarousel1" data-slide-to="2"></li>
        </ol>
    </div>

    </section>
    <!-- end slider section -->
</div>

<!-- shop section -->
<section class="shop_section layout_padding">
    <div class="container">
    <div class="heading_container heading_center">
        <h2>Latest Watches</h2>
    </div>
    <div class="row">
    {% for items in item %}
        <div class="col-sm-6 col-xl-3">
        <div class="box">
            <a href="">
            <div class="img-box">
                <img src="{{items.image.url}}" alt="">
            </div>
            <div class="detail-box">
                <h6>{{items.name}}</h6>
                {% comment %} <p>{{items.get_category_display}}</p> {% endcomment %}
                <h6>Price:$<span>{{items.price}}</span>
                </h6>
            </div>
            <div class="new {{items.get_label_display}}-color">
                <span>{{items.condition}}</span>
            </div>
            </a>
        </div>
        </div>
        {% endfor %}
    </div>
    <div class="btn-box">
        <a href="{% url 'watches' %}">View All</a>
    </div>
    </div>
</section>

<!-- end shop section -->
<!-- about section -->

<section class="about_section layout_padding">
    <div class="container  ">
    <div class="row">
        <div class="col-md-6 col-lg-5 ">
        <div class="img-box">
            <img src="{% static 'images/about-img.png' %}" alt="">
        </div>
        </div>
        <div class="col-md-6 col-lg-7">
        <div class="detail-box">
            <div class="heading_container">
            <h2>
                About Us
            </h2>
            </div>
            <p>
            There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration
            in some form, by injected humour, or randomised words which don't look even slightly believable. If you
            are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in
            the middle of text. All
            </p>
            <a href="{% url 'about' %}">
            Read More
            </a>
        </div>
        </div>
    </div>
    </div>
</section>

<!-- end about section -->
<!-- feature section -->

<section class="feature_section layout_padding">
    <div class="container">
    <div class="heading_container">
        <h2>
        Features Of Our Watches
        </h2>
        <p>
        Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </p>
    </div>
    <div class="row">
    {% for posts in post %}
        <div class="col-sm-6 col-lg-3">
        <div class="box">
            <div class="img-box">
            <img src="{{posts.image.url}}" alt="">
            </div>
            <div class="detail-box">
            <h5>{{posts.title}}</h5>
            <p>{{ posts.body|truncatechars:35}}</p>
            <a href="">
                <span>
                Read More
                </span>
                <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
            </a>
            </div>
        </div>
        </div>
        {% endfor %}
    </div>
    <div class="btn-box">
        <a href="">
        View More
        </a>
    </div>
    </div>
</section>

<!-- end feature section -->
<!-- contact section -->

<section class="contact_section">
    <div class="container">
    <div class="row">
        <div class="col-md-6">
        <div class="form_container">
            <div class="heading_container">
            <h2>
                Contact Us
            </h2>
            </div>
            <form action="">
            <div>
                <input type="text" placeholder="Full Name " />
            </div>
            <div>
                <input type="email" placeholder="Email" />
            </div>
            <div>
                <input type="text" placeholder="Phone number" />
            </div>
            <div>
                <input type="text" class="message-box" placeholder="Message" />
            </div>
            <div class="d-flex ">
                <button>SEND</button>
            </div>
            </form>
        </div>
        </div>
        <div class="col-md-6">
        <div class="img-box">
            <img src="{% static 'images/contact-img.jpg' %}" alt="">
        </div>
        </div>
    </div>
    </div>
</section>

<!-- end contact section -->
<!-- footer section -->

<footer class="footer_section mt-3">
<div class="container mt-3">
    <div class="row">
    <div class="col-md-6 col-lg-3 footer-col">
        <div class="footer_detail">
        <h4>
            About
        </h4>
        <p>
            Necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with
        </p>
        <div class="footer_social">
            <a href="">
            <i class="fa fa-instagram" aria-hidden="true"></i>
            </a>
            <a href="">
            <i class="fa fa-facebook" aria-hidden="true"></i>
            </a>
            <a href="">
            <i class="fa fa-youtube" aria-hidden="true"></i>
            </a>
            <a href="">
            <i class="fa fa-telegram" aria-hidden="true"></i>
            </a>
        </div>
        </div>
    </div>
    <div class="col-md-6 col-lg-3 footer-col">
        <div class="footer_contact">
        <h4>
            Reach at..
        </h4>
        <div class="contact_link_box">
            <a href="">
            <i class="fa fa-map-marker" aria-hidden="true"></i>
            <span>
                Location
            </span>
            </a>
            <a href="">
            <i class="fa fa-phone" aria-hidden="true"></i>
            <span>
                Call +01 1234567890
            </span>
            </a>
            <a href="">
            <i class="fa fa-envelope" aria-hidden="true"></i>
            <span>
                demo@gmail.com
            </span>
            </a>
        </div>
        </div>
    </div>
    <div class="col-md-6 col-lg-3 footer-col">
        <div class="footer_contact">
        <h4>
            Subscribe
        </h4>
        <form action="#">
            <input type="text" placeholder="Enter email" />
            <button type="submit">
            Subscribe
            </button>
        </form>
        </div>
    </div>
    <div class="col-md-6 col-lg-3 footer-col">
        <div class="map_container">
        <div class="map">
            <div id="googleMap"></div>
        </div>
        </div>
    </div>
    </div>
    <div class="footer-info">
    <p>
        &copy; <span id="displayYear"></span> All Rights Reserved By
        <a href="https://html.design/">Free Html Templates</a>
    </p>
    </div>
</div>
</footer>
<!-- footer section -->
<!-- jQery -->
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
</script>
<!-- bootstrap js -->
<script src="{% static 'js/bootstrap.js' %}"></script>
<!-- owl slider -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
</script>
<!-- custom js -->
<script src="{% static 'js/custom.js' %}"></script>
<!-- Google Map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
<!-- End Google Map -->
<body>
<html>

{% endblock %}

templates/watches.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- shop section -->
  <section class="shop_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>Latest Watches</h2>
      </div>
      <div class="row">
      {% for orders in order %}
        <div class="col-sm-6 col-xl-3">
        <div class="box">
            <a href="">
            <div class="img-box">
                <img src="{{orders.image.url}}" alt="">
            </div>
            <div class="detail-box">
                <h6>{{orders.name}}</h6>
                {% comment %} <p>{{items.get_category_display}}</p> {% endcomment %}
                <h6>Price:$<span>{{orders.price}}</span>
                </h6>
            </div>
            <div class="new {{orders.get_label_display}}-color">
                <span>{{orders.condition}}</span>
            </div>
            </a>
        </div>
        </div>
        {% endfor %}
      </div>
      <div class="heading_container heading_center mt-3">
        <h2>Latest Phone</h2>
      </div>
      <div class="row">
              {% comment %} <div class="detail-box {{orders.get_label_display}}-color">
                <span>{{orders.get_category_display}}</span> {% endcomment %}           
    </div>
  </section>

  <!-- end shop section -->
{% endblock %}
{% include 'footer.html' %}